---
- name: Setup synlogy NAS
  hosts: all
  become: true
  roles:
    - {role: system, tags: "system"}
    - {role: python, tags: "python"}
    - {role: docker, tags: "docker"}
    - {role: telegraf, tags: "telegraf"}
    - {role: grafana, tags: "grafana"}
    - {role: influxdb, tags: "influxdb"}
    - {role: pihole, tags: "pihole"}
    - {role: watchtower, tags: "watchtower"}
    - {role: fava, tags: "fava"}
    - {role: miniflux, tags: "miniflux"}
    - {role: paperless-ng, tags: "paperless-ng"}
    - {role: gramps, tags: "gramps"}
    - {role: caddy, tags: "caddy"}
    # tasks:
    # - name: Print all available facts
    #   ansible.builtin.debug:
    #     var: ansible_facts

- name: Setup synlogy NAS
  hosts: pi
  become: true
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
